### ISSUE TITLE
Install fails with SyntaxError: Unexpected token { in puppeteer/install.js:175

### ISSUE THREAD

**Issue by Krillle** [Brandawg93/homebridge-nest-cam#125]
```
sudo npm install -g --unsafe-perm homebridge-nest-cam

> puppeteer@3.3.0 install /usr/lib/node_modules/homebridge-nest-cam/node_modules/puppeteer
> node install.js

/usr/lib/node_modules/homebridge-nest-cam/node_modules/puppeteer/install.js:175
            } catch {
                    ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

**Comment by Krillle** [comment]
Puppeteer needs Node V10+
https://github.com/puppeteer/puppeteer/issues/5894
