### ISSUE TITLE
nodejs, upgraded to the latest version and now getting errors!

### ISSUE THREAD

**Issue by jvic1234** [Brandawg93/homebridge-nest-cam#162]
Hello,

This plugin was working perfectly but now after updating, I am getting errors.

(node:268) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'streamQuality' of undefined
    at NexusStreamer.startPlayback (/usr/lib/node_modules/homebridge-nest-cam/dist/streamer.js:222:37)
    at StreamingDelegate.handleStreamRequest (/usr/lib/node_modules/homebridge-nest-cam/dist/streaming-delegate.js:303:30)
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:268) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[8/2/2020, 16:14:59] [Nest-cam] [NexusStreamer] Connected
[8/2/2020, 16:15:19] [Nest-cam] [RETURN AUDIO] ffmpeg exited with code: 0 and signal: null (error)
(node:268) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'streamQuality' of undefined
    at NexusStreamer.startPlayback (/usr/lib/node_modules/homebridge-nest-cam/dist/streamer.js:222:37)
    at StreamingDelegate.handleStreamRequest (/usr/lib/node_modules/homebridge-nest-cam/dist/streaming-delegate.js:303:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[8/2/2020, 16:15:47] [Nest-cam] [NexusStreamer] Connected
[8/2/2020, 16:16:06] [Nest-cam] [RETURN AUDIO] ffmpeg exited with code: 0 and signal: null (error)

**Comment by Brandawg93** [comment]
That's definitely a bug. Thanks for the catch. As a quick fix, add `"streamQuality": 3` to the options of your config.json. I'll fix this permanently in the next release.

**Comment by jvic1234** [comment]
add "streamQuality": 3 results below

[8/2/2020, 16:47:57] [Nest-cam] [NexusStreamer] Connected
[8/2/2020, 16:47:58] [Nest-cam] [NexusStreamer] Redirecting...
[8/2/2020, 16:47:58] [Nest-cam] [NexusStreamer] Disconnected
[8/2/2020, 16:47:58] [Nest-cam] [NexusStreamer] Connected
[8/2/2020, 16:48:17] [Nest-cam] [RETURN AUDIO] ffmpeg exited with code: 0 and signal: null (error)
[8/2/2020, 16:48:27] [Nest-cam] [NexusStreamer] Disconnected

**Comment by Brandawg93** [comment]
That looks good. Return audio doesn't work on specific OSes.

**Comment by jvic1234** [comment]
running Raspberry pi 3, updated to the latest nodejs, npm, all updates applied.

"ffmpegCodec": "copy" works with sound
"ffmpegCodec": "libx64" no video, results in the error below

[8/2/2020, 16:47:57] [Nest-cam] [NexusStreamer] Connected
[8/2/2020, 16:47:58] [Nest-cam] [NexusStreamer] Redirecting...
[8/2/2020, 16:47:58] [Nest-cam] [NexusStreamer] Disconnected
[8/2/2020, 16:47:58] [Nest-cam] [NexusStreamer] Connected
[8/2/2020, 16:48:17] [Nest-cam] [RETURN AUDIO] ffmpeg exited with code: 0 and signal: null (error)
[8/2/2020, 16:48:27] [Nest-cam] [NexusStreamer] Disconnected

**Comment by Brandawg93** [comment]
It should be `libx264`.

**Comment by jvic1234** [comment]
sorry for the mistake, yes it works.

on raspberry pi3, should i use copy or linx264

**Comment by Brandawg93** [comment]
Personally, I use `libx264` because `copy` is too choppy, but I'm running on a Pi 4.

**Comment by jvic1234** [comment]
nevermind libx264 is super slow motion video 👍

**Comment by jvic1234** [comment]
yeah I think its time for me to ditch the pi3
