### ISSUE TITLE
err buffer out of bounds with latest version in hoobs

### ISSUE THREAD

**Issue by WIMWG** [Brandawg93/homebridge-nest-cam#292]
10/7/2020, 10:38:49 AM [homebridge-zp.ZPS1] warning: no zone players found
10/7/2020, 10:38:53 AM RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (internal/buffer.js:75:11)
    at Buffer.readUInt8 (internal/buffer.js:243:5)
    at NexusStreamer.handleNexusData (/home/hoobs/.hoobs/node_modules/homebridge-nest-cam/dist/nest/streamer.js:454:41)
    at WebSocket.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-nest-cam/dist/nest/streamer.js:101:18)
    at WebSocket.emit (events.js:310:20)
    at Receiver.receiverOnMessage (/home/hoobs/.hoobs/node_modules/ws/lib/websocket.js:797:20)
    at Receiver.emit (events.js:310:20)
    at Receiver.dataMessage (/home/hoobs/.hoobs/node_modules/ws/lib/receiver.js:428:14)
    at Receiver.getData (/home/hoobs/.hoobs/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/home/hoobs/.hoobs/node_modules/ws/lib/receiver.js:143:22)
10/7/2020, 10:38:53 AM Got SIGTERM, shutting down Bridge...
10/7/20

**Comment by Brandawg93** [comment]
Take a look at #284. My response would be similar to that one.

**Comment by Brandawg93** [comment]
I've published a new test that may fix this. You can install it via `npm -g i homebridge-nest-cam@5.4.2-test.0 --unsafe-perm`. Let me know if this fixes your issue.

**Comment by WIMWG** [comment]
I am sorry 
only have terminal inside hoobs
failed to install with permission errors
i am not expert level
i will wait for your next official release
thanks for your effort

Groeten
Wim

**Comment by Brandawg93** [comment]
You can install in hoobs terminal by navigating to the `node_modules` folder and running `npm i homebridge-nest-cam@5.4.2-test.0 --unsafe-perm`. Either way, these errors shouldn't break the hoobs process.

**Comment by WIMWG** [comment]
Still no success
i will wait



Groeten
Wim

**Comment by WIMWG** [comment]
uninstalling / installing did it 👍

Groeten
Wim

**Comment by Brandawg93** [comment]
Glad to hear this is working. This shouldn't happen anymore with v5.4.2.
