### ISSUE TITLE
homebridge-nest-cam throws error in logs when user stops viewing camera feed on iOS device. 

### ISSUE THREAD

**Issue by W0GER** [Brandawg93/homebridge-nest-cam#294]
**Describe the bug**
homebridge-nest-cam throws error in logs when user stops viewing camera feed on iOS device. 

**Debug Output**
```
Oct 07 11:37:57 raspberrypi homebridge[25408]: [10/7/2020, 11:37:57 AM] [Nest-cam] [NexusStreamer] Connected
Oct 07 11:37:57 raspberrypi homebridge[25408]: [10/7/2020, 11:37:57 AM] [Nest-cam] [NexusStreamer] Redirecting...
Oct 07 11:37:57 raspberrypi homebridge[25408]: [10/7/2020, 11:37:57 AM] [Nest-cam] [NexusStreamer] Disconnected
Oct 07 11:37:57 raspberrypi homebridge[25408]: [10/7/2020, 11:37:57 AM] [Nest-cam] [NexusStreamer] Connected
Oct 07 11:38:14 raspberrypi homebridge[25408]: [10/7/2020, 11:38:14 AM] [Nest-cam] [NexusStreamer] Talkback Begin
Oct 07 11:38:16 raspberrypi homebridge[25408]: [10/7/2020, 11:38:16 AM] [Nest-cam] [NexusStreamer] Talkback End
Oct 07 11:38:21 raspberrypi homebridge[25408]: [10/7/2020, 11:38:21 AM] [Nest-cam] [NexusStreamer] Disconnected
Oct 07 11:38:21 raspberrypi homebridge[25408]: (node:25408) UnhandledPromiseRejectionWarning: Error: write EPIPE
Oct 07 11:38:21 raspberrypi homebridge[25408]:     at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
Oct 07 11:38:21 raspberrypi homebridge[25408]: (Use `node --trace-warnings ...` to show where the warning was created)
Oct 07 11:38:21 raspberrypi homebridge[25408]: (node:25408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Oct 07 11:38:21 raspberrypi homebridge[25408]: (node:25408) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**

1. Homebridge configured with homebridge-nest-cam
1. Homebridge and cams added to Home app
1. Click on Doorbell video feed, wait for the live view to come up
1. Click the **X** at the top of the screen to exit the video preview
1. In the log the above output is logged. 

**Expected behavior**
The promise rejection should be handled so that in the future it doesn't terminate the Node.js process (causing homebridge to restart)

Please answer these questions before submitting this issue:
```
On what device are you running homebridge: Raspberry Pi
On what iOS version are you having issues: iOS 14.0.1
What camera types are having issues: Nest Hello, Nest Cam IQ Outdoor
Does this issue occur consistently or randomly: consistently
```

**Comment by Brandawg93** [comment]
I've published a new test that may fix this. You can install it via `npm -g i homebridge-nest-cam@5.4.2-test.0 --unsafe-perm`. Let me know if this fixes your issue.

**Comment by sensnowy** [comment]
Hi. I have the same issues but can’t use the fix #
![Uploading FB1F6E5E-2B70-4AF7-960C-29499B707F62.jpeg…]()

**Comment by sensnowy** [comment]
![57E8F0F4-660E-4988-A9D3-3639E2DCC041](https://user-images.githubusercontent.com/42115708/95689783-7f06dc00-0c13-11eb-9326-79e1c6f9debc.jpeg)

**Comment by W0GER** [comment]
I installed the version above and restarted homebridge. 

I don't see this any more on the Nest Cam cameras. 
Here's what is logged when I view and exit the video from the Nest Hello doorbell camera:

```
Oct 12 14:09:33 raspberrypi homebridge[1605]: [10/12/2020, 2:09:33 PM] [Nest-cam] [NexusStreamer] Connected
Oct 12 14:09:33 raspberrypi homebridge[1605]: [10/12/2020, 2:09:33 PM] [Nest-cam] [NexusStreamer] Redirecting...
Oct 12 14:09:33 raspberrypi homebridge[1605]: [10/12/2020, 2:09:33 PM] [Nest-cam] [NexusStreamer] Disconnected
Oct 12 14:09:34 raspberrypi homebridge[1605]: [10/12/2020, 2:09:34 PM] [Nest-cam] [NexusStreamer] Connected
Oct 12 14:09:49 raspberrypi homebridge[1605]: [10/12/2020, 2:09:49 PM] [Nest-cam] [NexusStreamer] Disconnected
Oct 12 14:09:49 raspberrypi homebridge[1605]: (node:1605) UnhandledPromiseRejectionWarning: Error: write EPIPE
Oct 12 14:09:49 raspberrypi homebridge[1605]:     at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
Oct 12 14:09:49 raspberrypi homebridge[1605]: (node:1605) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
```

**Comment by Brandawg93** [comment]
Does it actually break homebridge or are you just seeing the error in your logs?

**Comment by Brandawg93** [comment]
If you can, try these steps to produce a better output log for me:
1. Stop homebridge
2. Run `which homebridge`
3. Use above output to run `node --trace-warnings /path/to/homebridge`

This should give a complete stack trace of the error so I can see where it is occurring.

**Comment by W0GER** [comment]
Sure thing, here's the output. 

Clicked on "Front Door" Camera which is our Nest Hello doorbell. Then exited the video back to Favorites. 

```
[10/12/2020, 5:08:21 PM] [Nest-cam] [NexusStreamer] Connected
[10/12/2020, 5:08:22 PM] [Nest-cam] [NexusStreamer] Redirecting...
[10/12/2020, 5:08:22 PM] [Nest-cam] [NexusStreamer] Disconnected
[10/12/2020, 5:08:22 PM] [Nest-cam] [NexusStreamer] Connected
[10/12/2020, 5:08:39 PM] [Nest-cam] [NexusStreamer] Disconnected
(node:2249) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:2249) Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
(node:2249) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

**Comment by Brandawg93** [comment]
Unfortunately, I'm unable to recreate the issue and the above stack trace is less helpful than I thought it would be. Thanks for the attempt, though. I few more questions:
1. What version of node are you running?
2. What version homebridge are you running?

When looking at the code, I've added a handler to every possible place that EPIPE could be thrown. I'm just curious if it could be something with an older version of node or homebridge.

**Comment by deandrejones2002** [comment]
@Brandawg93 was there any resolution to this issue... i am seeing this issue as well
i am running 
homebridge-nest-cam v7.5.0
on HomeBridge v1.3.6
