### ISSUE TITLE
Instructions on how to get audio working

### ISSUE THREAD

**Issue by Brandtley** [Brandawg93/homebridge-nest-cam#38]
Could you post instructions on how to get audio working?  I am new at this and it is not clear to me how to get audio working from my nest cameras.

thank you, love the progress you are making.

**Comment by Brandawg93** [comment]
Audio should work out-of-the-box. Just make sure you _have not_ specified a `pathToFfmpeg`, (if you have, ensure that your custom ffmpeg is compiled with libfdk_aac support) and make sure your volume is turned up. The home app likes to turn your volume all the way before streaming.

**Comment by Brandtley** [comment]
Does not seem to be working.  What codec should I be using?  I currently have libx264 set.

**Comment by Brandawg93** [comment]
libx264 if fine. You may be looking at the old version of your cameras. Try uninstalling and reinstalling the plugin.

**Comment by Brandtley** [comment]
just uninstalled and reinstalled and nothing.  Not sure what could be going on

**Comment by Brandawg93** [comment]
When you run homebridge in debug mode (`homebridge-D`) do you see any errors?

**Comment by Brandtley** [comment]
the only errors that I see are the following
Error: listen EADDRINUSE: address already in use :::51826
    at Server.setupListenHandle [as _listen2] (net.js:1306:14)
    at listenInCluster (net.js:1354:12)
    at Server.listen (net.js:1442:7)
    at EventedHTTPServer._this.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:85:21)
    at HAPServer._this.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:258:22)
    at Bridge.Accessory._this.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:978:18)
    at Server.publishBridge (/usr/local/lib/node_modules/homebridge/src/server.ts:191:17)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:163:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:162:5)
[5/11/2020, 2:04:10 PM] Got SIGTERM, shutting down Homebridge...
[5/11/2020, 2:04:12 PM] [Config] Homebridge Config UI X v4.18.0 is listening on :: port 8080
[5/11/2020, 2:04:13 PM] [Config] Error: listen EADDRINUSE: address already in use :::8080
[5/11/2020, 2:04:13 PM] [Config] Another process or service on this host is using port 8080.
[5/11/2020, 2:04:13 PM] [Config] Please stop the other service or change the port you have assigned to homebridge-config-ui-x.
[5/11/2020, 2:04:13 PM] [Config] Ending process now.

**Comment by Brandawg93** [comment]
That is a Config UI issue. It looks like you have two instances of homebridge running.
```
[5/11/2020, 2:04:12 PM] [Config] Homebridge Config UI X v4.18.0 is listening on :: port 8080
[5/11/2020, 2:04:13 PM] [Config] Error: listen EADDRINUSE: address already in use :::8080
[5/11/2020, 2:04:13 PM] [Config] Another process or service on this host is using port 8080.
[5/11/2020, 2:04:13 PM] [Config] Please stop the other service or change the port you have assigned to homebridge-config-ui-x.
```

**Comment by Brandtley** [comment]
yeah, that is because I can't get home bridge to shutdown for some reason to run it in debug mode.  so I ran the homebridge -D in a another terminal window and it has those errors.

**Comment by Brandtley** [comment]
I think I figured out how to do it from the web interface.  Here is a copy of the log file in debug mode...
[5/11/2020, 2:37:03 PM] [Nest-cam] [NexusStreamer] Connected
[5/11/2020, 2:37:03 PM] [Nest-cam] [NexusStreamer] Redirecting...
[5/11/2020, 2:37:03 PM] [Nest-cam] [NexusStreamer] Disconnected
[5/11/2020, 2:37:03 PM] [Nest-cam] [NexusStreamer] Connected
[5/11/2020, 2:37:19 PM] [Nest-cam] [NexusStreamer] Disconnected
[5/11/2020, 2:38:23 PM] [Config] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: socket hang up
[5/11/2020, 2:44:29 PM] [Config] [admin] Accessory layout changes saved.
[5/11/2020, 2:49:34 PM] [Config] [admin] Accessory layout changes saved.
[5/11/2020, 2:49:37 PM] [Nest-cam] Setting Backyard (Backyard) to off
[5/11/2020, 2:49:45 PM] [Config] [admin] Accessory layout changes saved.
[5/11/2020, 2:49:49 PM] [Nest-cam] Setting Backyard (Backyard) to on
[5/11/2020, 2:51:01 PM] [Config] Changes to config.json saved.
[5/11/2020, 2:51:05 PM] [Config] Homebridge restart request received
[5/11/2020, 2:51:06 PM] [Config] No restart command defined, killing process...
[5/11/2020, 2:51:06 PM] Got SIGTERM, shutting down Homebridge...
[5/11/2020, 2:51:12 PM] Loaded config.json with 0 accessories and 3 platforms.
[5/11/2020, 2:51:12 PM] ---
[5/11/2020, 2:51:13 PM] Loaded plugin: homebridge-config-ui-x
[5/11/2020, 2:51:13 PM] Registering platform 'homebridge-config-ui-x.config'
[5/11/2020, 2:51:13 PM] ---
[5/11/2020, 2:51:13 PM] Loaded plugin: homebridge-nest
[5/11/2020, 2:51:13 PM] Registering platform 'homebridge-nest.Nest'
[5/11/2020, 2:51:13 PM] ---
[5/11/2020, 2:51:13 PM] Loaded plugin: homebridge-nest-cam2
[5/11/2020, 2:51:13 PM] Registering platform 'homebridge-nest-cam2.Nest-cam'
[5/11/2020, 2:51:13 PM] ---
[5/11/2020, 2:51:13 PM] Loading 3 platforms...
[5/11/2020, 2:51:13 PM] [Config] Initializing config platform...
[5/11/2020, 2:51:13 PM] [Config] Spawning homebridge-config-ui-x with PID 1471
[5/11/2020, 2:51:13 PM] [Nest] Initializing Nest platform...
[5/11/2020, 2:51:13 PM] [Nest] Fetching Nest devices.
[5/11/2020, 2:51:13 PM] [Nest-cam] Initializing Nest-cam platform...
[5/11/2020, 2:51:13 PM] [Nest-cam] Configuring accessory Backyard (Backyard)
[5/11/2020, 2:51:13 PM] [Nest-cam] Configuring accessory Front Yard (Front Yard)
[5/11/2020, 2:51:13 PM] [Nest-cam] Configuring accessory Garage
[5/11/2020, 2:51:16 PM] [Config] Starting Nest application...
[5/11/2020, 2:51:16 PM] [Config] ConfigModule dependencies initialized
[5/11/2020, 2:51:16 PM] [Config] LoggerModule dependencies initialized
[5/11/2020, 2:51:16 PM] [Config] PassportModule dependencies initialized
[5/11/2020, 2:51:16 PM] [Config] CustomPluginsModule dependencies initialized
[5/11/2020, 2:51:16 PM] [Config] PlatformToolsModule dependencies initialized
[5/11/2020, 2:51:16 PM] [Config] JwtModule dependencies initialized
[5/11/2020, 2:51:16 PM] [Config] AppModule dependencies initialized
[5/11/2020, 2:51:16 PM] [Config] LogModule dependencies initialized
[5/11/2020, 2:51:16 PM] [Config] AccessoriesModule dependencies initialized
[5/11/2020, 2:51:16 PM] [Config] TerminalModule dependencies initialized
[5/11/2020, 2:51:16 PM] [Config] HbServiceModule dependencies initialized
[5/11/2020, 2:51:16 PM] [Config] ConfigEditorModule dependencies initialized
[5/11/2020, 2:51:16 PM] [Config] HomebridgeRingModule dependencies initialized
[5/11/2020, 2:51:16 PM] [Config] LinuxModule dependencies initialized
[5/11/2020, 2:51:16 PM] [Config] DockerModule dependencies initialized
[5/11/2020, 2:51:16 PM] [Config] StatusModule dependencies initialized
[5/11/2020, 2:51:16 PM] [Config] UsersModule dependencies initialized
[5/11/2020, 2:51:16 PM] [Config] ServerModule dependencies initialized
[5/11/2020, 2:51:16 PM] [Config] PluginsModule dependencies initialized
[5/11/2020, 2:51:16 PM] [Config] AuthModule dependencies initialized
[5/11/2020, 2:51:16 PM] [Config] BackupModule dependencies initialized
[5/11/2020, 2:51:16 PM] [Config] Homebridge Config UI X v4.18.0 is listening on :: port 8080
[5/11/2020, 2:51:16 PM] [Config] AppController {/api}:
[5/11/2020, 2:51:16 PM] [Config] Mapped {/api, GET} route
[5/11/2020, 2:51:16 PM] [Config] AuthController {/api/auth}:
[5/11/2020, 2:51:16 PM] [Config] Mapped {/api/auth/login, POST} route
[5/11/2020, 2:51:16 PM] [Config] Mapped {/api/auth/settings, GET} route
[5/11/2020, 2:51:16 PM] [Config] Mapped {/api/auth/noauth, POST} route
[5/11/2020, 2:51:16 PM] [Config] Mapped {/api/auth/check, GET} route
[5/11/2020, 2:51:16 PM] [Config] ServerController {/api/server}:
[5/11/2020, 2:51:16 PM] [Config] Mapped {/api/server/restart, PUT} route
[5/11/2020, 2:51:16 PM] [Config] Mapped {/api/server/qrcode.svg, GET} route
[5/11/2020, 2:51:16 PM] [Config] Mapped {/api/server/reset-homebridge-accessory, PUT} route
[5/11/2020, 2:51:16 PM] [Config] Mapped {/api/server/reset-cached-accessories, PUT} route
[5/11/2020, 2:51:16 PM] [Config] ConfigEditorController {/api/config-editor}:
[5/11/2020, 2:51:16 PM] [Config] Mapped {/api/config-editor, GET} route
[5/11/2020, 2:51:16 PM] [Config] Mapped {/api/config-editor, POST} route
[5/11/2020, 2:51:16 PM] [Config] Mapped {/api/config-editor/backups, GET} route
[5/11/2020, 2:51:16 PM] [Config] Mapped {/api/config-editor/backups/:backupId(\d+), GET} route
[5/11/2020, 2:51:16 PM] [Config] Mapped {/api/config-editor/backups, DELETE} route
[5/11/2020, 2:51:16 PM] [Config] PluginsController {/api/plugins}:
[5/11/2020, 2:51:16 PM] [Config] Mapped {/api/plugins, GET} route
[5/11/2020, 2:51:16 PM] [Config] Mapped {/api/plugins/search/:query, GET} route
[5/11/2020, 2:51:16 PM] [Config] Mapped {/api/plugins/config-schema/:pluginName, GET} route
[5/11/2020, 2:51:16 PM] [Config] Mapped {/api/plugins/changelog/:pluginName, GET} route
[5/11/2020, 2:51:17 PM] [Config] Mapped {/api/plugins/release/:pluginName, GET} route
[5/11/2020, 2:51:17 PM] [Config] HomebridgeRingController {/api/plugins/custom-plugins/homebridge-ring}:
[5/11/2020, 2:51:17 PM] [Config] Mapped {/api/plugins/custom-plugins/homebridge-ring/exchange-credentials, POST} route
[5/11/2020, 2:51:17 PM] [Config] UsersController {/api/users}:
[5/11/2020, 2:51:17 PM] [Config] Mapped {/api/users, GET} route
[5/11/2020, 2:51:17 PM] [Config] Mapped {/api/users, POST} route
[5/11/2020, 2:51:17 PM] [Config] Mapped {/api/users/:userId(\d+), PATCH} route
[5/11/2020, 2:51:17 PM] [Config] Mapped {/api/users/:userId(\d+), DELETE} route
[5/11/2020, 2:51:17 PM] [Config] LinuxController {/api/platform-tools/linux}:
[5/11/2020, 2:51:17 PM] [Config] Mapped {/api/platform-tools/linux/restart-host, PUT} route
[5/11/2020, 2:51:17 PM] [Config] Mapped {/api/platform-tools/linux/shutdown-host, PUT} route
[5/11/2020, 2:51:17 PM] [Config] DockerController {/api/platform-tools/docker}:
[5/11/2020, 2:51:17 PM] [Config] Mapped {/api/platform-tools/docker/startup-script, GET} route
[5/11/2020, 2:51:17 PM] [Config] Mapped {/api/platform-tools/docker/startup-script, PUT} route
[5/11/2020, 2:51:17 PM] [Config] Mapped {/api/platform-tools/docker/restart-container, PUT} route
[5/11/2020, 2:51:17 PM] [Config] Mapped {/api/platform-tools/docker/env, GET} route
[5/11/2020, 2:51:17 PM] [Config] Mapped {/api/platform-tools/docker/env, PUT} route
[5/11/2020, 2:51:17 PM] [Config] HbServiceController {/api/platform-tools/hb-service}:
[5/11/2020, 2:51:17 PM] [Config] Mapped {/api/platform-tools/hb-service/homebridge-startup-settings, GET} route
[5/11/2020, 2:51:17 PM] [Config] Mapped {/api/platform-tools/hb-service/homebridge-startup-settings, PUT} route
[5/11/2020, 2:51:17 PM] [Config] Mapped {/api/platform-tools/hb-service/set-full-service-restart-flag, PUT} route
[5/11/2020, 2:51:17 PM] [Config] BackupController {/api/backup}:
[5/11/2020, 2:51:17 PM] [Config] Mapped {/api/backup/download, GET} route
[5/11/2020, 2:51:17 PM] [Config] Mapped {/api/backup/restore, POST} route
[5/11/2020, 2:51:17 PM] [Config] Mapped {/api/backup/restart, PUT} route
[5/11/2020, 2:51:17 PM] [Config] Nest application successfully started
[1589223077181] INFO  (1471 on Brandts-iMac.rochester.rr.com): Server listening at http://[::]:8080
[5/11/2020, 2:51:18 PM] [Nest] initing thermostat "Dinning Rm Thermostat": deviceId: 01AA02AB101207DH structureId: 2fa09191-61f7-11ea-961d-0aa51bef2578
[5/11/2020, 2:51:18 PM] [Nest] initing home_away_sensor "Home Occupied": deviceId: 2fa09191-61f7-11ea-961d-0aa51bef2578 structureId: 2fa09191-61f7-11ea-961d-0aa51bef2578
[5/11/2020, 2:51:18 PM] Initializing platform accessory 'Dinning Rm Thermostat'...
[5/11/2020, 2:51:18 PM] Initializing platform accessory 'Home Occupied'...
Setup Payload:
X-HM://0023IX8JIGP4J
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
[1589223078289] INFO  (1471 on Brandts-iMac.rochester.rr.com): incoming request
    reqId: 1
    req: {
      "method": "GET",
      "url": "/api/auth/check",
      "hostname": "localhost:8080",
      "remoteAddress": "::1",
      "remotePort": 51576
    }
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 033-44-254 │     
    └────────────┘     
                       
[1589223078342] INFO  (1471 on Brandts-iMac.rochester.rr.com): request completed
    reqId: 1
    res: {
      "statusCode": 200
    }
    responseTime: 51.45834100013599
[5/11/2020, 2:51:18 PM] Homebridge is running on port 51826.
[1589223078399] INFO  (1471 on Brandts-iMac.rochester.rr.com): incoming request
    reqId: 2
    req: {
      "method": "GET",
      "url": "/api/auth/settings",
      "hostname": "localhost:8080",
      "remoteAddress": "::1",
      "remotePort": 51574
    }
[1589223078405] INFO  (1471 on Brandts-iMac.rochester.rr.com): request completed
    reqId: 2
    res: {
      "statusCode": 200
    }
    responseTime: 5.54555799998343
[1589223078530] INFO  (1471 on Brandts-iMac.rochester.rr.com): incoming request
    reqId: 3
    req: {
      "method": "GET",
      "url": "/api/server/qrcode.svg",
      "hostname": "localhost:8080",
      "remoteAddress": "::1",
      "remotePort": 51574
    }
[1589223078620] INFO  (1471 on Brandts-iMac.rochester.rr.com): request completed
    reqId: 3
    res: {
      "statusCode": 200
    }
    responseTime: 88.98020399990492
[5/11/2020, 2:51:39 PM] [Nest-cam] [NexusStreamer] Connected
[5/11/2020, 2:51:39 PM] [Nest-cam] [NexusStreamer] Redirecting...
[5/11/2020, 2:51:39 PM] [Nest-cam] [NexusStreamer] Disconnected
[5/11/2020, 2:51:39 PM] [Nest-cam] [NexusStreamer] Connected
[5/11/2020, 2:51:54 PM] [Nest-cam] [NexusStreamer] Disconnected

**Comment by Brandawg93** [comment]
It doesn't look like you are running in debug mode. You will see much more output between `connected` and `disconnected` if so.

**Comment by Brandtley** [comment]
I turn debug on for accessories and this is what I saw
[5/11/2020, 3:05:27 PM] [Config] [HapClient] [192.168.1.254:51826 (CB:22:3D:E2:CE:31)] Connected
[5/11/2020, 3:05:27 PM] [Config] [HapClient] Discovery :: Re-broadcasting discovery query
[5/11/2020, 3:05:38 PM] [Config] [HapClient] [192.168.1.254:51826 (CB:22:3D:E2:CE:31)] Got Event: [{"aid":7,"iid":24,"value":"AQEB"}]
[5/11/2020, 3:05:38 PM] [Nest-cam] [NexusStreamer] Connected
[5/11/2020, 3:05:39 PM] [Nest-cam] [NexusStreamer] Redirecting...
[5/11/2020, 3:05:39 PM] [Nest-cam] [NexusStreamer] Disconnected
[5/11/2020, 3:05:39 PM] [Nest-cam] [NexusStreamer] Connected
[5/11/2020, 3:05:52 PM] [Config] [HapClient] [192.168.1.254:51826 (CB:22:3D:E2:CE:31)] Got Event: [{"aid":7,"iid":24,"value":"AQEA"}]
[5/11/2020, 3:05:52 PM] [Config] [HapClient] [192.168.1.254:51826 (CB:22:3D:E2:CE:31)] Got Event: [{"aid":8,"iid":24,"value":"AQEB"}]
[5/11/2020, 3:05:52 PM] [Nest-cam] [NexusStreamer] Disconnected
[5/11/2020, 3:05:53 PM] [Nest-cam] [NexusStreamer] Connected
[5/11/2020, 3:05:53 PM] [Nest-cam] [NexusStreamer] Redirecting...
[5/11/2020, 3:05:53 PM] [Nest-cam] [NexusStreamer] Disconnected
[5/11/2020, 3:05:53 PM] [Nest-cam] [NexusStreamer] Connected
[5/11/2020, 3:06:02 PM] [Config] [HapClient] [192.168.1.254:51826 (CB:22:3D:E2:CE:31)] Got Event: [{"aid":8,"iid":24,"value":"AQEA"}]
[5/11/2020, 3:06:02 PM] [Nest-cam] [NexusStreamer] Disconnected
[5/11/2020, 3:06:06 PM] [Config] [HapClient] [192.168.1.254:51826 (CB:22:3D:E2:CE:31)] Got Event: [{"aid":9,"iid":16,"value":"AQEB"}]
[5/11/2020, 3:06:06 PM] [Nest-cam] [NexusStreamer] Connected
[5/11/2020, 3:06:07 PM] [Nest-cam] [NexusStreamer] Redirecting...
[5/11/2020, 3:06:07 PM] [Nest-cam] [NexusStreamer] Disconnected
[5/11/2020, 3:06:07 PM] [Nest-cam] [NexusStreamer] Connected
[5/11/2020, 3:06:19 PM] [Config] [HapClient] [192.168.1.254:51826 (CB:22:3D:E2:CE:31)] Got Event: [{"aid":9,"iid":16,"value":"AQEA"}]
[5/11/2020, 3:06:19 PM] [Nest-cam] [NexusStreamer] Disconnected
[5/11/2020, 3:06:21 PM] [Config] [HapClient] Discovery :: Ended
[5/11/2020, 3:06:39 PM] [Config] [HapClient] [192.168.1.254:51826 (CB:22:3D:E2:CE:31)] Disconnected
[1589223999163] INFO  (2123 on Brandts-iMac.rochester.rr.com): incoming request

**Comment by Brandawg93** [comment]
I don't see anything wrong in the logs. I've asked a few other users and all have confirmed that audio is working for them. It could be a mac issue as not many other users are running homebridge on a mac. The only other thing I can think of to try is to recompile ffmpeg and specify its location using the `pathToFfmpeg` option.

**Comment by Brandtley** [comment]
ok thanks, just curious what others are using are they using Pi's or running windows?

**Comment by Brandawg93** [comment]
Mostly Pi's. I've seen a few Windows users, but they've had more problems than Macs.

**Comment by Kampe** [comment]
I run this in docker compose on a rpi 3 and see the same behavior with the latest version with the "rpi" optimized compiled ffmpeg binary.

**Comment by Brandawg93** [comment]
I’m also running homebridge on an RPi 4 using docker compose. If you run homebridge in debug mode (`homebridge -D`) you should see extra logs and probably some errors.

**Comment by Brandtley** [comment]
Getting the following error when connecting to camera after latest update.  I am wondering if this has something to do with why I am not hearing audio.
[5/21/2020, 12:57:49 PM] [Nest-cam] [NexusStreamer] Connected
[5/21/2020, 12:57:52 PM] [Nest-cam] [AUDIO] ffmpeg exited with code: 1 and signal: null (error)

**Comment by Brandawg93** [comment]
Oh good. I was hoping the latest update would help you see some more informative logs. Yes. Your ffmpeg is not properly configured to use libfdk_aac. Not sure what your particular fix would be, but that seems to be the issue.

**Comment by Brandtley** [comment]
I have looked at the options for ffmpeg and it appears that libfdk_aac is enabled, do I need to add a path statement?

**Comment by Brandtley** [comment]
finally got it working.  I found a site to recompile with libfdk_aac enabled.  thanks continuing to provide us with new features

**Comment by Brandawg93** [comment]
Great to hear it!

**Comment by popepay** [comment]
I get an error when trying to compile ffmpeg with the ibfdk_aac plugin. 
`[...] --enable-libfdk-aac
ERROR: libfdk_aac not found`

This is on a Raspberry pi 3B+ with Raspbian GNU/Linux 8.0 (jessie).
I was able to get the Nest Cam video feeds thanks to this plugin, but the audio is not working. 

Any help appreciated

**Comment by popepay** [comment]
I ended up following the following instructions, and this solved my problem. Audio is now working.
