### ISSUE TITLE
Cant Login to my google account

### ISSUE THREAD

**Issue by satopy** [Brandawg93/homebridge-nest-cam#386]
I installed the plugin on Homebridge today. However, there is no way to change from the Loggin in. Please wait ... screen, and no matter how many times the setup is repeated, it does not work.
At first I was using an account with two-step verification, but it seemed difficult, so I set up family sharing and used an account without two-step verification, but I couldn't.

OS | Raspbian GNU/Linux Buster (10)
Node.js version | v14.15.1
Npm version | v6.14.9
HomeBridge version | v1.1.6

**Comment by Brandawg93** [comment]
Have you tried authenticating [manually](https://github.com/Brandawg93/homebridge-nest-cam/wiki/Manual-Authentication)?

**Comment by satopy** [comment]
Yes. I have already tried it. In fact, the homebridge-nest plugin is working fine. Only homebridge-nest-cam didn't work.

**Comment by Brandawg93** [comment]
Ok. You should be able to use the same credentials for both plugins. Do you see any errors in the logs?

**Comment by satopy** [comment]
`[13/12/2020, 02:17:02] Error: The requested platform 'Nest-cam' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:387:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)`

This is the error log.

**Comment by Brandawg93** [comment]
That means the plugin is not installed or homebridge cannot find the plugin. Usually, this means the plugin was installed globally and needs to be installed locally instead. I would recommend using the UI to install the plugin.

**Comment by satopy** [comment]
I see...I had to write the code after installing it in the UI. I'm sorry for my lack of experience. I've solved the problem.
