### ISSUE TITLE
Error configuring v2

### ISSUE THREAD

**Issue by jqnatividad** [Brandawg93/homebridge-nest-cam#39]
After installing v2.0, my previously working setup stopped working and I got this error:

```
5/11/2020, 4:40:27 PM [Nest-cam] Configuring accessory Living Room
5/11/2020, 4:40:27 PM [Nest-cam] Error fetching cameras: 
5/11/2020, 4:40:27 PM [Nest-cam] TypeError: accessory.configureController is not a function
    at NestCamPlatform.configureAccessory (/home/hoobs/.hoobs/node_modules/homebridge-nest-cam2/dist/index.js:135:19)
    at response.items.forEach (/home/hoobs/.hoobs/node_modules/homebridge-nest-cam2/dist/index.js:222:26)
    at Array.forEach (<anonymous>)
    at NestCamPlatform.addCameras (/home/hoobs/.hoobs/node_modules/homebridge-nest-cam2/dist/index.js:208:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I uninstalled and reinstalled the plugin without success.

I’m currently running HOOBS 3.2.3 on a Raspberry Pi 3 Model B.

**Comment by Brandawg93** [comment]
Since HOOBS is a fork of homebridge, their code is different. I didn't know this until now. Unfortunaly, HOOBS will no longer be supported going forward. If you would like to continue using HOOBS feel free to use an older version of this plugin using `npm -g i homebridge-nest-cam2@hoobs`.

**Comment by Brandawg93** [comment]
FYI, as of HOOBS 3, this plugin now works again.
