### ISSUE TITLE
homebridge-nest-cam v7.0.0 can not authenticate - incoming request error

### ISSUE THREAD

**Issue by cjattard** [Brandawg93/homebridge-nest-cam#398]
**Describe the bug**
can not authenticate with homebridge-nest-cam v7.0.0
**Debug Output**

[1/29/2021, 11:41:08] [Homebridge UI] Running Command: sudo -E -n npm install -g homebridge-nest-cam@latest
[1/29/2021, 11:41:53] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /generateToken
[1/29/2021, 11:42:01] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /login
[1/29/2021, 11:42:10] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /username
[1/29/2021, 11:42:14] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /password
[1/29/2021, 11:42:23] [Homebridge UI] [homebridge-nest-cam] Invalid request url.
[1/29/2021, 11:44:00] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /stop
[1/29/2021, 11:44:04] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /login
[1/29/2021, 11:44:13] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /username
[1/29/2021, 11:44:17] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /password
[1/29/2021, 11:44:18] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /stop
[1/29/2021, 11:44:18] [Homebridge UI] [homebridge-nest-cam] Unable to find login button.
[1/29/2021, 11:44:46] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /generateToken
[1/29/2021, 11:44:58] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /login
[1/29/2021, 11:45:01] [Homebridge UI] [homebridge-nest-cam] Terminating child process...
[1/29/2021, 11:45:01] [Homebridge UI] [homebridge-nest-cam] Child process ended
[1/29/2021, 11:45:07] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /username
[1/29/2021, 11:45:11] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /password
[1/29/2021, 11:45:20] [Homebridge UI] [homebridge-nest-cam] Invalid request url.
[1/29/2021, 11:45:50] [Homebridge UI] [homebridge-nest-cam] Terminating child process...
[1/29/2021, 11:45:50] [Homebridge UI] [homebridge-nest-cam] Child process ended

**To Reproduce**

1. 

**Expected behavior**

Please answer these questions before submitting this issue:
```
On what device are you running homebridge: 
On what iOS version are you having issues: 
What camera types are having issues: 
Does this issue occur consistently or randomly: 
If applicable, what was the last version that worked properly: 
```

**Comment by cjattard** [comment]
manual authentication doesn't work either, when copying the URL I am taken to the google login page, I enter my credentials and it asks for permission to link nest to my google account (which I already have) and then throws me to google.com

**Comment by Brandawg93** [comment]
It is supposed to throw you to google.com. As long as you have `Preserve Log` checked, you will see the correct call in the console. Hint: it will probably be in red.

**Comment by cjattard** [comment]
Ok manual did work thanks for the pointer. the automated method did fail again after reinstalling the plugin. its now chucking up an error about zones

[1/29/2021, 12:26:26] [Nest-cam] Error getting zones for Front Door (Doorbell) camera: 403
Troubleshoot here: https://github.com/Brandawg93/homebridge-nest-cam/wiki/Error-Codes
[1/29/2021, 12:26:26] [Nest-cam] Error getting zones for Living Room (Camera) camera: 403
Troubleshoot here: https://github.com/Brandawg93/homebridge-nest-cam/wiki/Error-Codes
[1/29/2021, 12:26:26] [Nest-cam] TypeError: Cannot read property 'nest_user_id' of undefined
    at NestSession.<anonymous> (/usr/local/lib/node_modules/homebridge-nest-cam/src/nest/session.ts:69:39)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-nest-cam/dist/nest/session.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[1/29/2021, 12:26:26] [Nest-cam] Error getting zones for xx (Camera) camera: 403
Troubleshoot here: https://github.com/Brandawg93/homebridge-nest-cam/wiki/Error-Codes
[1/29/2021, 12:26:26] [Nest-cam] Error checking alerts: 403
Troubleshoot here: https://github.com/Brandawg93/homebridge-nest-cam/wiki/Error-Codes
[1/29/2021, 12:26:26] [Nest-cam] Error getting zones for Study (Camera) camera: 403
Troubleshoot here: https://github.com/Brandawg93/homebridge-nest-cam/wiki/Error-Codes
INFO: SmartThings-v2 Hub Communication Established
[1/29/2021, 12:26:28] [Nest-cam] TypeError: Cannot read property 'nest_user_id' of undefined
    at NestSession.<anonymous> (/usr/local/lib/node_modules/homebridge-nest-cam/src/nest/session.ts:69:39)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-nest-cam/dist/nest/session.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by Brandawg93** [comment]
You may need to delete your accessory cache. The good thing about the new login method is that you should only need to do it once. Not weekly like the old method.

**Comment by sensnowy** [comment]
hey. 
i got a similar issue. It will not take my authy code and keeps on requestion for an 2FA code. 
any idea how i can fix this? 
since it is about log in, i will psot here isntead of making a new one.

**Comment by Brandawg93** [comment]
@sensnowy Try the manual authentication. I know a lot of users may have trouble getting their refresh token for the first time, but this way, you won't have to log back in periodically.

**Comment by dabrowm1** [comment]
Same issue, 403 error. Using Hoobs 3.3.2. I got the Refresh Token using the manual authentication method. Sorry to be a noob but how do I delete the accessory cache?

**Comment by Brandawg93** [comment]
@dabrowm1 I'm not sure with HOOBS. I assume there are `accessories` and `persist` folders that you can delete, buy you may want to reach out to HOOBS just to be sure.

**Comment by danremollino** [comment]
I am also having issues with the token authentication. Using the automated method, the HB log outputs the log below...

```
[1/29/2021, 6:19:53 PM] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /generateToken
[1/29/2021, 6:20:43 PM] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /login
[1/29/2021, 6:20:48 PM] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /username
[1/29/2021, 6:20:50 PM] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /password
[1/29/2021, 6:20:59 PM] [Homebridge UI] [homebridge-nest-cam] Could not get code. Error: Error: Request failed with status code 400
[1/29/2021, 6:21:43 PM] [Homebridge UI] [homebridge-nest-cam] Terminating child process...
[1/29/2021, 6:21:43 PM] [Homebridge UI] [homebridge-nest-cam] Child process ended
```

I have tried numerous times using the manual method, but after editing my config.json and restarting HB I get the output below at start...

```
[1/29/2021, 5:10:37 PM] [Nest-cam] You must provide a refreshToken in config.json. Please see README.md for instructions
```

...even though `refreshToken` is added.

I cleared my two accessories cache from HB which removed them from the Home app as expected, but I have yet to re-discover them.

Let me know if I can provide more information.

**Comment by Brandawg93** [comment]
I've added backwards compatibility for the old browser cookies in v7.0.2. Feel free to continue using this method of authentication. Instructions for the old method are also on the [wiki](https://github.com/Brandawg93/homebridge-nest-cam/wiki/Manual-Authentication). Make sure you remove the `refreshToken` before using the old method.

**Comment by danremollino** [comment]
> I've added backwards compatibility for the old browser cookies in v7.0.2. Feel free to continue using this method of authentication. Instructions for the old method are also on the [wiki](https://github.com/Brandawg93/homebridge-nest-cam/wiki/Manual-Authentication). Make sure you remove the `refreshToken` before using the old method.

Thanks. Back up and running.

**Comment by sensnowy** [comment]
[30/01/2021, 11:35:34] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /totp
[30/01/2021, 11:35:34] [Homebridge UI] [homebridge-nest-cam] Incorrect totp. Please try again.
[30/01/2021, 11:35:42] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /totp
[30/01/2021, 11:35:42] [Homebridge UI] [homebridge-nest-cam] Incorrect totp. Please try again.
[30/01/2021, 11:36:34] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /totp
[30/01/2021, 11:36:34] [Homebridge UI] [homebridge-nest-cam] Incorrect totp. Please try again.
[30/01/2021, 11:36:48] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /totp
[30/01/2021, 11:36:48] [Homebridge UI] [homebridge-nest-cam] Incorrect totp. Please try again.
[30/01/2021, 11:37:03] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /totp
[30/01/2021, 11:37:03] [Homebridge UI] [homebridge-nest-cam] Incorrect totp. Please try again.
[30/01/2021, 11:37:04] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /stop
[30/01/2021, 11:37:05] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /login
[30/01/2021, 11:37:10] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /username
[30/01/2021, 11:37:11] [Homebridge UI] [homebridge-nest-cam] Incoming Request: /totp
[30/01/2021, 11:37:11] [Homebridge UI] [homebridge-nest-cam] Unable to find login button.
[30/01/2021, 11:37:12] [Homebridge UI] [homebridge-nest-cam] Unable to find input field for password.




these are my current reports. i figured out it needs to be the same totp from the time you hit login. nothing afterwards. need to time it right. looks like it does not refresh itself to retrieve and check the totp.

**Comment by cherk947** [comment]
Same issue here.  Found that I have to use Chrome Browser but still no dice.  Getting the following:

Unable to find input field for password

or 

Could not get code. Error: Request failed with status code 400

**Comment by Brandawg93** [comment]
Please use the old browser cookies or use the new manual authentication method for the time being.

**Comment by sensnowy** [comment]
That works fine for me. Btw there is a weird visual glitch for me. I have to put the browser into dark mode to be able to read the context of the sign in screen. Just wanted to pass up the info. Love the work thank you for what you do.

**Comment by cherk947** [comment]
Now I am getting Unable to find input field for password.

**Comment by Brandawg93** [comment]
[Manual Authentication](https://github.com/Brandawg93/homebridge-nest-cam/wiki/Manual-Authentication)

**Comment by cjattard** [comment]
Quick update my end. I removed the plug-in. Then manually removed cached accessories related to the plug-in. I was then able to restart HB reinstall the plug-in and although the automatic method of auth failed the manual method worked fine. 

Thanks for updating and looking into this. Awesome work.

**Comment by Brandawg93** [comment]
v7.1.0 has been published. The auto-login process has been removed since it only worked for a small number of users. I've made errors more informative in the login process as well. If anyone still has issues, let me know.

**Comment by cherk947** [comment]
@Brandawg93   Working like a champ today!  Thanks
