### ISSUE TITLE
[Bug]: TypeError: Cannot read property 'nest_user_id' of undefined

### ISSUE THREAD

**Issue by jb1228** [Brandawg93/homebridge-nest-cam#445]
### Describe the bug

Using the Google refreshToken method, I am unable to login via the UI or using the manual method. 

This had previously been working flawlessly (even on the latest version of 7.4.1) until I logged out, and I haven't been able to log back in again. The `homebridge-nest` plugin is also currently working fine using the same Google refreshToken method. 

I've tried deleting the cached accessories, uninstalling/reinstalling the plugin from scratch, and even tried a few previous versions. 

Feel free to let me know if I can provide any additional information.

### Debug Output

[9/30/2021, 11:25:51 PM] Loaded plugin: homebridge-nest-cam@7.4.1
[9/30/2021, 11:25:51 PM] Registering platform 'homebridge-nest-cam.Nest-cam'
[9/30/2021, 11:25:51 PM] [homebridge-nest-cam] Launched child bridge with PID 6460
[9/30/2021, 11:25:51 PM] Registering platform 'homebridge-nest-cam.Nest-cam'
[9/30/2021, 11:25:51 PM] [homebridge-nest-cam] Loaded homebridge-nest-cam v7.4.1 child bridge successfully
[9/30/2021, 11:25:51 PM] [homebridge-nest-cam] Using motionDetection from config: false
[9/30/2021, 11:25:51 PM] [homebridge-nest-cam] Using doorbellAlerts from config: true
[9/30/2021, 11:25:51 PM] [homebridge-nest-cam] Using doorbellSwitch from config: false
[9/30/2021, 11:25:51 PM] [homebridge-nest-cam] Using streamingSwitch from config: false
[9/30/2021, 11:25:51 PM] [homebridge-nest-cam] Using chimeSwitch from config: false
[9/30/2021, 11:25:51 PM] [homebridge-nest-cam] Using announcementsSwitch from config: true
[9/30/2021, 11:25:51 PM] [homebridge-nest-cam] Using audioSwitch from config: false
[9/30/2021, 11:25:51 PM] [homebridge-nest-cam] Defaulting structures to []
[9/30/2021, 11:25:51 PM] [homebridge-nest-cam] Defaulting cameras to []
Preparing Advertiser for 'homebridge-nest-cam AE54' using ciao backend!
[9/30/2021, 11:25:51 PM] [homebridge-nest-cam] Authenticating via Google refresh token.
Starting to advertise 'homebridge-nest-cam AE54' using ciao backend!
[9/30/2021, 11:25:51 PM] Homebridge v1.3.4 (homebridge-nest-cam) is running on port 55963.
[9/30/2021, 11:25:52 PM] [homebridge-nest-cam] TypeError: Cannot read property 'nest_user_id' of undefined
    at NestSession.<anonymous> (/usr/lib/node_modules/homebridge-nest-cam/src/nest/session.ts:69:39)
    at fulfilled (/usr/lib/node_modules/homebridge-nest-cam/dist/nest/session.js:5:58)
[9/30/2021, 11:25:52 PM] [homebridge-nest-cam] TypeError: Cannot read property 'nest_user_id' of undefined
    at NestSession.<anonymous> (/usr/lib/node_modules/homebridge-nest-cam/src/nest/session.ts:69:39)
    at fulfilled (/usr/lib/node_modules/homebridge-nest-cam/dist/nest/session.js:5:58)

### Steps to reproduce

1. Logged out
2. Attempted to log back in

### Device Type

Debian 4.19.132-1 (2020-07-24) x86_64 (Virtual Machine)

### iOS Version

N/A

### Camera Types

N/A

### Bug Persistence

Consistently

### Last Working Version

7.4.1

**Comment by jb1228** [comment]
NEVERMIND! I was using the wrong Google account.
