### ISSUE TITLE
[Bug]: still "no response" after FAQ and troubleshooting

### ISSUE THREAD

**Issue by brandonlind** [Brandawg93/homebridge-nest-cam#473]
### Describe the bug

I've followed the FAQ for solving this issue but I still have "no response" on my nest cams despite updated thumbnails. My nest cams are not the newest nest cams, they are a few years old.

I saw at some point ffpmeg error in the Homebridge log, so I installed with homebrew using flags for fdk_ac and speex. I've pointed to that install in the homebridge-nest-cam advanced settings. This removed the red error from the logs but had no effect on "no response" from cameras when attempting to stream from Home app on iPhone.

homebridge server is running on a mac, I'm attempting to view cameras on my iPhone. macOS and iOS all up to date.

homebridge up to date

I've attempted to uninstall and reinstall homebridge-nest-cam but no effect.

I can stream the same cameras from the Nest app.

### Debug Output

[3/2/2022, 10:15:02 AM] Loaded config.json with 0 accessories and 4 platforms.
[3/2/2022, 10:15:02 AM] Loaded 5 cached accessories from cachedAccessories.
[3/2/2022, 10:15:02 AM] ---
[3/2/2022, 10:15:03 AM] Loaded plugin: homebridge-blink-for-home@3.7.6
[3/2/2022, 10:15:03 AM] Registering platform 'homebridge-blink-for-home.Blink'
[3/2/2022, 10:15:03 AM] ---
[3/2/2022, 10:15:03 AM] Loaded plugin: homebridge-config-ui-x@4.42.0
[3/2/2022, 10:15:03 AM] Registering platform 'homebridge-config-ui-x.config'
[3/2/2022, 10:15:03 AM] ---
[3/2/2022, 10:15:03 AM] Loaded plugin: homebridge-nest-cam@7.5.0
[3/2/2022, 10:15:03 AM] Registering platform 'homebridge-nest-cam.Nest-cam'
[3/2/2022, 10:15:03 AM] ---
[3/2/2022, 10:15:03 AM] Loaded plugin: homebridge-ring@9.24.0
[3/2/2022, 10:15:03 AM] Registering platform 'homebridge-ring.Ring'
[3/2/2022, 10:15:03 AM] ---
[3/2/2022, 10:15:03 AM] Loading 4 platforms...
[3/2/2022, 10:15:03 AM] [Config] Initializing config platform...
[3/2/2022, 10:15:03 AM] [Config] Spawning homebridge-config-ui-x with PID 5506
[3/2/2022, 10:15:03 AM] [Ring] Initializing Ring platform...
[3/2/2022, 10:15:03 AM] [Blink] Initializing Blink platform...
[3/2/2022, 10:15:03 AM] [Nest-cam] Initializing Nest-cam platform...
[3/2/2022, 10:15:03 AM] [Nest-cam] Using motionDetection from config: true
[3/2/2022, 10:15:03 AM] [Nest-cam] Defaulting doorbellAlerts to true
[3/2/2022, 10:15:03 AM] [Nest-cam] Defaulting doorbellSwitch to true
[3/2/2022, 10:15:03 AM] [Nest-cam] Using streamingSwitch from config: true
[3/2/2022, 10:15:03 AM] [Nest-cam] Defaulting chimeSwitch to true
[3/2/2022, 10:15:03 AM] [Nest-cam] Using announcementsSwitch from config: true
[3/2/2022, 10:15:03 AM] [Nest-cam] Using audioSwitch from config: true
[3/2/2022, 10:15:03 AM] [Nest-cam] Defaulting structures to []
[3/2/2022, 10:15:03 AM] [Nest-cam] Using cameras from config: REDACTED6
[3/2/2022, 10:15:03 AM] [Ring] Configuring cached accessory REDACTED7 Front Door
[3/2/2022, 10:15:03 AM] [Ring] [Circular]
[3/2/2022, 10:15:03 AM] [Nest-cam] Configuring accessory REDACTED1
[3/2/2022, 10:15:03 AM] [Nest-cam] Using alertTypes from config: Motion,Sound,Person
[3/2/2022, 10:15:03 AM] [Nest-cam] Using importantOnly from config: true
[3/2/2022, 10:15:03 AM] [Nest-cam] Creating microphone for REDACTED1.
[3/2/2022, 10:15:03 AM] [Nest-cam] Creating switch for REDACTED1 Streaming.
[3/2/2022, 10:15:03 AM] [Nest-cam] Creating switch for REDACTED1 Audio.
[3/2/2022, 10:15:03 AM] [Nest-cam] Configuring accessory REDACTED2
[3/2/2022, 10:15:03 AM] [Nest-cam] Using alertTypes from config: Motion,Sound,Person
[3/2/2022, 10:15:03 AM] [Nest-cam] Using importantOnly from config: true
[3/2/2022, 10:15:03 AM] [Nest-cam] Creating microphone for REDACTED2.
[3/2/2022, 10:15:03 AM] [Nest-cam] Creating switch for REDACTED2 Streaming.
[3/2/2022, 10:15:03 AM] [Nest-cam] Creating switch for REDACTED2 Audio.
[3/2/2022, 10:15:03 AM] [Ring] didFinishLaunching
[3/2/2022, 10:15:03 AM] [Blink] Init Blink
[3/2/2022, 10:15:03 AM] [Nest-cam] Authenticating via Google refresh token.
[3/2/2022, 10:15:03 AM] Publishing bridge accessory (name: Homebridge 3535, publishInfo: {
  username: 'REDACTED8',
  port: 51790,
  pincode: '***-**-***',
  category: 2,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: undefined
}).
Setup Payload:
X-HM://0024JV0PCW4GX
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:

*REDACTED3*

Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌─────────────┐
    │ *REDACTED4* │
    └─────────────┘

[3/2/2022, 10:15:03 AM] Error: listen EADDRINUSE: address already in use :::51790
    at Server.setupListenHandle [as _listen2] (node:net:1334:16)
    at listenInCluster (node:net:1382:12)
    at Server.listen (node:net:1469:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:155:20)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:332:21)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1279:18)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
[3/2/2022, 10:15:03 AM] Got SIGTERM, shutting down Homebridge...
[3/2/2022, 10:15:04 AM] [Ring] Found the following locations:
[3/2/2022, 10:15:04 AM] [Ring]   locationId: REDACTED9 - REDACTED10
[3/2/2022, 10:15:04 AM] [Ring] Configuring 1 cameras and 1 devices for location "REDACTED10" - locationId: REDACTED9
[3/2/2022, 10:15:04 AM] [Blink] Initing: Blink:Network:REDACTED11
[3/2/2022, 10:15:04 AM] [Blink] Initing: Blink:Network:REDACTED11:Camera:REDACTED12
[3/2/2022, 10:15:04 AM] [Blink] Blink Home Blink Sync Module Armed (Target) for Blink Home Blink Sync Module is: 3
[3/2/2022, 10:15:04 AM] [Blink] Blink Home Blink Sync Module Arm for Blink Home Blink Sync Module is: Manual Arm
[3/2/2022, 10:15:04 AM] [Blink] Battery State for Blink Office REDACTED5 is: 2
[3/2/2022, 10:15:04 AM] [Blink] Temperature for Blink Office REDACTED5 is: 21.7
[3/2/2022, 10:15:04 AM] [Blink] Temperature Sensor Active for Blink Office REDACTED5 is: true
[3/2/2022, 10:15:04 AM] [Blink] Blink Home Blink Sync Module Armed (Current) for Blink Home Blink Sync Module is: 3
[3/2/2022, 10:15:04 AM] [Nest-cam] Filtering cameras by cameras config
[3/2/2022, 10:15:04 AM] [Nest-cam] Creating motion sensor for REDACTED1 Motion.
[3/2/2022, 10:15:04 AM] [Nest-cam] Creating motion sensor for REDACTED1 Sound.
[3/2/2022, 10:15:04 AM] [Nest-cam] Creating motion sensor for REDACTED1 Person.
[3/2/2022, 10:15:04 AM] [Nest-cam] Creating motion sensor for REDACTED2 Motion.
[3/2/2022, 10:15:04 AM] [Nest-cam] Creating motion sensor for REDACTED2 Sound.
[3/2/2022, 10:15:04 AM] [Nest-cam] Creating motion sensor for REDACTED2 Person.
[3/2/2022, 10:15:04 AM] [Blink] Battery Level for Blink Office REDACTED5 is: 69
[3/2/2022, 10:15:05 AM] [Homebridge UI] Homebridge Config UI X v4.42.0 is listening on :: port 8581
[3/2/2022, 10:15:05 AM] [Homebridge UI] Error: listen EADDRINUSE: address already in use :::8581
[3/2/2022, 10:15:05 AM] [Homebridge UI] Another process or service on this host is using port 8581.
[3/2/2022, 10:15:05 AM] [Homebridge UI] Please stop the other service or change the port you have assigned to homebridge-config-ui-x.
[3/2/2022, 10:15:05 AM] [Homebridge UI] Ending process now.

### Steps to reproduce

1. open Home app on iPhone, I can see updated thumbnails but I cannot stream video.

### Device Type

Macbook Pro with macOS 12.2.1

### iOS Version

iOS 15.3.1

### Camera Types

black indoor Nest Cam

### Bug Persistence

Consistently

**Comment by brandonlind** [comment]
Not stale

**Comment by rfiorentino1** [comment]
I'm also having this no response issue with no luck, and have been racking my brain as to what's causing it. Other cameras, like ring, work just fine, and I've even put this plugin on it's own child bridge to isolate it. As far as I can tell, my logs look normal, about to open another issue in a second but wanted to comment here. Your logs seem like you have some IP address conflicts, or multiple instances of Homebridge running that are conflicting with each other. Likely not directly related to this plugin but something I noticed while skimming through. I'm also running Homebridge from a Mac, most people I think usually run from a Pi etc.

**Comment by rfiorentino1** [comment]
Just finally got things working consistently, I had to change the codec that the stream was using. For me, either copy, or h264_video_toolbox made the stream work consistently. Have you tried all of the possible codecs in the list?

**Comment by brandonlind** [comment]
@rfiorentino1 how did you update the codecs? TIA

**Comment by rfiorentino1** [comment]
The easiest way to do it is through the UI, instead of manually editing the config file. In the UI, go to the nest cam plug in settings, then click advanced settings. You should see a text field for ffmpeg codec, that currently says Libx264. Step through the list of Kodax, and see which ones work for you if any. After you change to another codec, save/restart homebridge for the change to take effect. Try "copy" first, and if that works, try other ones to see if they are better or worse quality

**Comment by brandonlind** [comment]
That was perfect! Changing the codec to 'copy' instead of 'libx264' worked for me and I can now stream the Nest cams from the Hope app. Thank you!!
