### ISSUE TITLE
Error loading camera after initial install

### ISSUE THREAD

**Issue by mmorper** [Brandawg93/homebridge-nest-cam#49]
Hey there... I've completed the initial install, including ffmpeg. It seems my token, cookies, etc parameters are correct as I can see the name of my Nest camera returning in the log below "Garage (Bikes)" however, I am unclear what the rest of the error is indicating. Suffice it to say, I am unable to see the camera in HOOBS and am unclear how to advance my troubleshooting.  
```
5/16/2020, 3:16:02 PM [Nest-cam] Configuring accessory Garage (Bikes)
5/16/2020, 3:16:02 PM [Nest-cam] Error fetching cameras: 
5/16/2020, 3:16:02 PM [Nest-cam] TypeError: accessory.configureController is not a function
    at NestCamPlatform.configureAccessory (/home/hoobs/.hoobs/node_modules/homebridge-nest-cam2/dist/index.js:135:19)
    at response.items.forEach (/home/hoobs/.hoobs/node_modules/homebridge-nest-cam2/dist/index.js:222:26)
    at Array.forEach (<anonymous>)
    at NestCamPlatform.addCameras (/home/hoobs/.hoobs/node_modules/homebridge-nest-cam2/dist/index.js:208:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
HOOBS Core 3.2.3
Node: 10.18.0

Thanks in advance for creating this plugin and the assistance.

**Comment by Brandawg93** [comment]
#39
