### ISSUE TITLE
Nest Cameras no longer load in Homebridge

### ISSUE THREAD

**Issue by jw172** [Brandawg93/homebridge-nest-cam#83]
After no changes to my config, i am now receiving the following errors in the Homebridge log file:

[6/12/2020, 12:52:02 PM] [Nest-cam] Error fetching cameras: 
[6/12/2020, 12:52:02 PM] [Nest-cam] TypeError: Cannot read property 'includes' of undefined
    at NestCamPlatform.configureAccessory (/usr/local/lib/node_modules/homebridge-nest-cam/src/index.ts:182:35)
    at /usr/local/lib/node_modules/homebridge-nest-cam/src/index.ts:273:16
    at Array.forEach (<anonymous>)
    at NestCamPlatform.addCameras (/usr/local/lib/node_modules/homebridge-nest-cam/src/index.ts:254:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at NestCamPlatform.didFinishLaunching (/usr/local/lib/node_modules/homebridge-nest-cam/src/index.ts:335:7)

Please help

1. Restart Homebridge
2. View log file

Include with your bug report this version info:
```
node --12.18.0
homebridge --1.1.0
```

**Comment by bustedtheory** [comment]
@jw172 I'm seeing the same, as are some others in the Discord channel. As of yesterday, I noticed my thermostat is having trouble keeping the correct state within HomeKit (though sending commands does work). Tried a re-auth with google and noticed the prefix on the "cookies" blob has changed... I think Google screwed with their backend

**Comment by Brandawg93** [comment]
They definitely did. I've already fixed it in development and have a test version ready. Would you mind testing if for me before I push it to everyone? You can install it via `npm -g i homebridge-nest-cam@test`.

**Comment by jw172** [comment]
Thanks @Brandawg93 but just installed your fix and have exactly the same issue :-)

**Comment by jw172** [comment]
Some additional info - also using Homebridge Nest plugin for Thermostat and Protect with no current issues (using same Google auth)

**Comment by Brandawg93** [comment]
I just published my latest changes. How about now?

**Comment by jw172** [comment]
Awesome @Brandawg93 it's perfect again. Appreciate your help :-)

**Comment by Brandawg93** [comment]
Whew. Great to hear it! I'll publish an official release soon.
